server:
  port: 8080
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/sbms_db?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: sbms_db
    username: root
    password: 12345
logging:
  level:
    org.springframework.security: DEBUG
springdoc:
  swagger-ui:
    path: ${SWAGGER_UI_PATH:/swagger-ui.html}